package com.askaragoz.supportagent.domain;

import com.askaragoz.supportagent.domain.converter.FloatArrayToVectorConverter;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity representing an article in the knowledge base.
 * Articles are semantically indexed via a 1536-dimension embedding vector
 * and retrieved by cosine similarity during RAG (Retrieval-Augmented Generation).
 */
@Entity
@Table(name = "knowledge_articles")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class KnowledgeArticle {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false)
    private String title;

    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;

    /**
     * 1536-dimension vector embedding of the article content.
     * Generated by OpenAI's text-embedding-3-small model during article creation or update.
     *
     * @Convert                       — applies FloatArrayToVectorConverter to translate between
     *                                  float[] (Java) and pgvector's "[v1,v2,...]" string format.
     * columnDefinition = "vector(1536)" — tells Flyway/Hibernate the exact PostgreSQL column type.
     *                                    1536 matches text-embedding-3-small's output dimension exactly.
     *                                    Changing this value would invalidate all stored embeddings.
     *
     * Nullable: true — seed articles start with no embedding; it is populated asynchronously
     * by the knowledge service after the article is saved.
     */
    @Convert(converter = FloatArrayToVectorConverter.class)
    @Column(columnDefinition = "vector(1536)")
    /*
     * @ColumnTransformer(write = "?::vector"):
     * Without this, Hibernate binds the parameter as 'character varying' (the converter's
     * output type). PostgreSQL rejects null::varchar for a vector column with:
     *   "column is of type vector but expression is of type character varying"
     * The cast ?::vector wraps every INSERT/UPDATE parameter so PostgreSQL receives the
     * value as the correct type — including NULL, which becomes NULL::vector.
     */
    @org.hibernate.annotations.ColumnTransformer(write = "?::vector")
    private float[] embedding;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private LocalDateTime updatedAt;
}
