package com.askaragoz.supportagent.mapper;

import com.askaragoz.supportagent.domain.KnowledgeArticle;
import com.askaragoz.supportagent.dto.request.KnowledgeArticleRequest;
import com.askaragoz.supportagent.dto.response.KnowledgeArticleResponse;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

/**
 * MapStruct mapper for KnowledgeArticle ↔ DTOs.
 */
@Mapper(componentModel = "spring")
public interface KnowledgeArticleMapper {

    /** Maps entity → response DTO. */
    KnowledgeArticleResponse toResponse(KnowledgeArticle article);

    /**
     * Maps request DTO → new entity for creation.
     *
     * @Mapping(ignore = true) — tells MapStruct to skip these target fields.
     * They must NOT be set from the request:
     *   id        — generated by the database (gen_random_uuid())
     *   embedding — populated by the AI service, not the client
     *   createdAt / updatedAt — managed by @CreationTimestamp / @UpdateTimestamp
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "embedding", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    KnowledgeArticle toEntity(KnowledgeArticleRequest request);

    /**
     * Updates an existing entity in place for PUT requests.
     *
     * @MappingTarget — tells MapStruct that 'article' is the object to write into,
     * not a source to read from. The generated code calls article.setTitle(...)
     * and article.setContent(...) rather than creating a new object.
     * Same ignores apply — never overwrite generated fields from request data.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "embedding", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateEntity(KnowledgeArticleRequest request, @MappingTarget KnowledgeArticle article);
}
